### ISSUE TITLE
How to implement an async convention that requires Mono.Cecil

### ISSUE THREAD

**Issue by michael-wolfenden** [andrewabest/Conventional#3]
I was thinking of adding a new async convention that for library code checks whether all tasks that are awaited have `ConfigureAwait(false)` set.
 
This requires the use of Mono.Cecil to detect, however the conventions are split into seperate 'Async' and 'Cecil' projects.

What do you suggest?

**Comment by andrewabest** [comment]
The initial reason behind the split was due to Conventional targeting.net 4.5, and I needed to support .net 4.0. So most of the 'core' conventions stayed in the base 'Conventional' project and it was downgraded to .net 4.0, and a .net 4.5 targeted project was created - at the time - purely to house the async conventions, hence the name.

In hindsight it is probably a little limiting. The intention of the separation of the projects is to allow the core conventions to be housed in a relatively slim package without additional dependencies, while conventions that require additional tooling or dependencies can be housed in an appropriately named package that depends on the core package. 

With this in mind I'm thinking of renaming the Conventional.Async project to Conventional.Net45

The last twist of complexity here is that the Conventional.Cecil package also targets .Net 4.0. So this would necessitate the creation of a Conventional.Cecil.Net45 project and package to house your convention.

Thoughts? I'm happy to make the changes, and I think this structure should accommodate most of the future growth on the backlog at the moment.

**Comment by michael-wolfenden** [comment]
So to clarify, are you proposing the following:

Project | Target | Convention
--------|--------|--------
Conventional | .Net 4.0 | Core conventions
Conventional.Net45 | .Net 4.5 | Current async conventions
Conventional.Cecil | .Net 4.0 | Current cecil conventions
Conventional.Cecil.Net45 | .Net 4.5 | New async & cecil convention

If so, then:

1. To use all the asynx conventions I would need to import three packages `Conventional`,  `Conventional.Net45` and `Conventional.Cecil.Net45`
2. The package names no longer make it clear what package I should get. For example I should only import the `Conventional.Net45` if I want async conventions, not just because I'm targeting .Net 4.5.

Is it important to extract the Cecil conventions into their own package?. If not then I would go with:

Project | Target | Convention
--------|--------|--------
Conventional | .Net 4.0 | Core conventions & Current cecil conventions
Conventional.Async | .Net 4.5 | Current async conventions & New async & cecil convention

Its a tough call.

**Comment by andrewabest** [comment]
> The package names no longer make it clear what package I should get.

Agreed.

> Is it important to extract the Cecil conventions into their own package?

The original reason for this was to not completely couple Conventional to Cecil, as the bulk of Conventional's functionality didn't leverage it. That being said, having to know of the implementation detail of the convention in order to select the correct package *stinks*.

The only thing that sets my spidey sense off with this approach is when a convention arises that is .net 4.5 specific but not async. That being said, if that occurs it might be time to move to a more sophisticated targeting approach - the current approach is nice and simple, so I'm keen to wring a little more out of it before investing in complexity :)

I'll go ahead with consolidating the current structure to Conventional / Conventional.Async as suggested over the next couple of nights.

**Comment by michael-wolfenden** [comment]
> The only thing that sets my spidey sense off with this approach is when a convention arises that is .net 4.5 specific but not async

Hmmm.. Hadn't considered this.

There is one other option

Project | Target | Convention
--------|--------|--------
Conventional | .Net 4.0 | Core conventions & Current cecil conventions
Conventional.Net45 | .Net 4.5 | Core conventions & Current cecil conventions & Current async conventions & New async & cecil convention

Basically, `Conventional.Net45` has all the conventions from `Conventional`, plus any 4.5 specific ones.  The `Conventional.Net45` project just add links all the files from the `Conventional` project.

Thoughts?

**Comment by andrewabest** [comment]
:) that was where I started with this, but then took the 'path of least resistance' to get to where I wanted to go. Going to have a play now, will update this with how I go. Thanks a lot for your input, I appreciate it :+1:

**Comment by michael-wolfenden** [comment]
No problem, happy to help

**Comment by andrewabest** [comment]
All done - I've gone with the linked file approach as it gives the flexibility needed, while keeping everything simple from an API point of view, and should make contribution fairly easy too. Let me know how you get along, and I'll close this off once you've given the :shipit:

**Comment by andrewabest** [comment]
@michael-wolfenden I'm going to close this issue off, you should be able to add your convention now if you wish :)
